name: music_service
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  aqueduct: ^3.3.0
  mime: any
  image: any
  watcher: ^0.9.7+14
  csv: ^4.0.3
  http_server: 0.9.8+3
  dart_tags: ^0.2.3

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
